"""add_provider_crm_tables

Revision ID: 8e286a231a3a
Revises: 27f1fc87cd6c
Create Date: 2025-06-08 19:47:05.701598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e286a231a3a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('primary_specialty', sa.String(length=200), nullable=False),
    sa.Column('primary_practice_name', sa.String(length=300), nullable=True),
    sa.Column('primary_practice_address', sa.String(length=500), nullable=True),
    sa.Column('primary_practice_city', sa.String(length=100), nullable=True),
    sa.Column('primary_practice_state', sa.String(length=2), nullable=True),
    sa.Column('primary_practice_zip', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_npi'), 'providers', ['npi'], unique=True)
    op.create_table('outreach_efforts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('outreach_date', sa.DateTime(), nullable=False),
    sa.Column('outreach_type', sa.String(length=100), nullable=False),
    sa.Column('outreach_specialist', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.String(length=10), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outreach_efforts_follow_up', 'outreach_efforts', ['follow_up_required', 'follow_up_date'], unique=False)
    op.create_index('idx_outreach_efforts_provider_date', 'outreach_efforts', ['provider_id', 'outreach_date'], unique=False)
    op.create_index('idx_outreach_efforts_specialist', 'outreach_efforts', ['outreach_specialist'], unique=False)
    op.create_index('idx_outreach_efforts_type', 'outreach_efforts', ['outreach_type'], unique=False)
    op.create_table('provider_referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referring_provider_id', sa.UUID(), nullable=False),
    sa.Column('referred_to_provider_id', sa.UUID(), nullable=False),
    sa.Column('referral_reason', sa.String(length=500), nullable=False),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.Column('referral_start_date', sa.DateTime(), nullable=False),
    sa.Column('referral_end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_to_provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['referring_provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_referrals_provider_pair', 'provider_referrals', ['referring_provider_id', 'referred_to_provider_id'], unique=False)
    op.create_index('idx_provider_referrals_reason', 'provider_referrals', ['referral_reason'], unique=False)
    op.create_index('idx_provider_referrals_referred_to_period', 'provider_referrals', ['referred_to_provider_id', 'referral_start_date', 'referral_end_date'], unique=False)
    op.create_index('idx_provider_referrals_referring_period', 'provider_referrals', ['referring_provider_id', 'referral_start_date', 'referral_end_date'], unique=False)
    op.create_table('provider_visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(length=200), nullable=False),
    sa.Column('practice_location', sa.String(length=500), nullable=True),
    sa.Column('services_rendered', sa.String(length=500), nullable=True),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('total_charges', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('visit_start_date', sa.DateTime(), nullable=False),
    sa.Column('visit_end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_visits_provider_period', 'provider_visits', ['provider_id', 'visit_start_date', 'visit_end_date'], unique=False)
    op.create_index('idx_provider_visits_specialty', 'provider_visits', ['specialty'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_provider_visits_specialty', table_name='provider_visits')
    op.drop_index('idx_provider_visits_provider_period', table_name='provider_visits')
    op.drop_table('provider_visits')
    op.drop_index('idx_provider_referrals_referring_period', table_name='provider_referrals')
    op.drop_index('idx_provider_referrals_referred_to_period', table_name='provider_referrals')
    op.drop_index('idx_provider_referrals_reason', table_name='provider_referrals')
    op.drop_index('idx_provider_referrals_provider_pair', table_name='provider_referrals')
    op.drop_table('provider_referrals')
    op.drop_index('idx_outreach_efforts_type', table_name='outreach_efforts')
    op.drop_index('idx_outreach_efforts_specialist', table_name='outreach_efforts')
    op.drop_index('idx_outreach_efforts_provider_date', table_name='outreach_efforts')
    op.drop_index('idx_outreach_efforts_follow_up', table_name='outreach_efforts')
    op.drop_table('outreach_efforts')
    op.drop_index(op.f('ix_providers_npi'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
