FROM python:3.10-slim-buster

RUN groupadd -r celery && useradd -r -g celery celery

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

ADD app/requirements.txt .

RUN pip install -r requirements.txt watchdog

ADD app/ /app

RUN chown -R celery:celery /app

USER celery

CMD ["sh", "-c", "watchmedo auto-restart --directory=./ --pattern='*.py' --recursive -- celery -A tasks.celery_config worker --loglevel=info --concurrency=1"]
