FROM python:3.10-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app

ADD app/requirements.txt .
RUN pip install -r requirements.txt

ADD app/ /app

RUN chmod +x /app/start.sh

EXPOSE 8080

CMD ["/app/start.sh"]