FROM python:3.12.8-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

RUN groupadd -r celery && useradd -r -g celery celery

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/

WORKDIR /app

ADD pyproject.toml .
RUN uv pip install --system -r pyproject.toml
RUN uv pip install --system watchdog

ADD app/ /app

RUN chown -R celery:celery /app

USER celery

CMD ["celery", "-A", "worker.config", "worker", "--loglevel=info", "--pool=solo"]